from locators.base_page_locators import BasePageLocator

class CreateAccountPage(BasePageLocator):
    SELECTTITLE = "//label[contains(.,'{title}')]//parent::div//input"
    FIRSTNAME = "customer_firstname"
    LASTNAME = "customer_lastname"
    PASSWORD = "passwd"
    BIRTHDAY = "days"
    BIRTHMONTH = "months"
    BIRTHYEAR = "years"
    NEWSLETTERCHECKBOX = "//label[contains(text(),'Sign up for our newsletter!')]//parent::div//input"
    SPECIALOFFERCHECKBOX = "//label[contains(text(),'Receive special offers from our partners!')]//parent::div//input"
    COMPANTNAME = "company"
    ADDRESS1 = "address1"
    ADDRESS2 = "address2"
    CITY = "city"
    POSTCODE = "postcode"
    OTHERINFO = "other"
    PHONENUMBER ="phone"
    MOBILENUMBER ="phone_mobile"
    STATE = "id_state"
    COUNTRY = "id_country"
    RIGSTERBUTTON = "//span[text()='Register']//parent::button"
