from selenium.webdriver.common.by import By

from locators.base_page_locators import BasePageLocator


class OwnerCommercialPageLocators(BasePageLocator):
    LOGIN_WITH_OWNER_COMMERCIAL = "//div[@class='toggle-label'][text()='Commercial']"
    PROPERTY_LABEL = "//div[@class='property-type-label'] [text()='Office'] "
    RENT = "//div[@class='toggle-label' and text()='Rent']"
    SELL = "//div[@class='toggle-label' and text()='Sell']"
    COUNTRY_CODE = "//div[@class='country-code']/span[text()='+91']"
    ENTER_MOBILE1 = "//div[contains(@class, 'material-input dropdownContainer') and .//text()='Enter Phone Number']"
    ENTER_MOBILE = "//input[@type='tel']"
    ENTER_NAME = "//input[@type='text']"
    SELECT_CITY2 = "//div[@class='country-code']/span[text()='Pune']"
    SELECT_CITY = "//*[@id='app-root']/div/div/div/div[2]/div[1]/div[2]/div/div[6]/div/div/div/input"
    SELECT_CITYP = "//input[contains(@value, 'Pune')]"
    SELCT_CITYPU = "//li[@class='opt selected' and text()='Pune']"
    START_NOW = "//button[@class='new-btn secondary  login large' and text()='Next, add address & price']"
    START_NOW2 = "//*[@id='app-root']/div/div/div/div[2]/div/div[2]/div/div[6]/button"
    START_NOW1 = "new-btn secondary  login large"
    #SCROLL_BAR = "//span[@class='css-yhp13m']"
    SCROLL_BAR = (By.XPATH, "//span[@class='css-yhp13m']")
    APARTMENT = "//div[@class='property-type-label' and text()='Apartment']"
    BUILDING = "//input[@type='text']"
    READY_TO_MOVE = "//div[@class='toggle-label'][text()='Ready to move']"
    LOCALITY = "//*[@id='app-root']/div/div/section/div[2]/div[2]/div/div/div[1]/div[2]/div/div[1]/input"
    MOVETOLOCALITY = "//*[@id='app-root']/div/div/section/div[2]/div[2]/div/div/div[1]/div[2]/div/div[1]/ul/li[1]"
    LOCALITY_LIST = "//ul[@class='result-cont']/li"
    ENTER_LOCALITY = "//li[@class='opt']"
    AVAILABLE_DATE = "//*[@id='app-root']/div/div/section/div[2]/div[2]/div/div/div[1]/div[5]/div/div/input"
    SELECT_DATE = "//div[@class='pmu-button' and text()='5']"
    AVAILABLE = "//div/label[@class='label' and text()='Available From']"
    ENTER_DATE = "/html/body/div[5]/div/div[3]/div[7]"
    PROPERTY_AGE = "//div[1]/div[6]/div/input"
    PROPERTY_ZONE =  "//div[@class='toggle-label' and text()= 'Commercial']"
    PROPERTY_HUB = "//div[@class='toggle-label' and text()= 'Business Park']"
    PROPERTY_CONDITION =  "//div[@class='toggle-label' and text()= 'Bare shell']"
    BUIlt_UP = "//div[11]/div/input"
    OWNERSHIP =  "//div[@class='toggle-label' and text()= 'Freehold']"
    CONSTRUCTION_STATUS = "//div[@class='toggle-label' and text()= 'No walls']"
    FLORING = "//div[@class='toggle-label' and text()= 'Marble']"
    EXPECTED_RENT =  "//div[16]/div/input"
    EXPECTED_DEPOSITE = "//div[17]/div/input"
    NEGOTIATION = "//div[@class='rf-group radio-group is_negotiable']/div/div"
    UPS_CHARGES = "//div[@class='rf-group radio-group dg_and_ups_charge_included']/div/div"
    ELECTRICITY_CHARGE =  "//div[@class='rf-group radio-group electricity_charges_included']/div/div"
    WATER_CHARGES = "//div[@class='rf-group radio-group water_charges_included']/div/div"
    LOCK_IN_PERIOD = "//div[22]/div/input"
    TOTAL_FLOR = "//div[25]/div/input"
    SELECT_Flor = "//div[6]/span"
    PASSENGERS_LIFT = "//div[29]/div/input"
    SERVICE_LIFT = "//div[30]/div/input"
    NEXTTOAMMETIES = "//button[@class='selfupload-cta-button css-1olr0sc']"
    ADDAMMENITIESBUTTON = "//div/button[@class='css-1olr0sc']"
    YOURFLORARROW = "//span[@class='icon icon-arrow-down']"
    YOUR_FLOR = (By.XPATH, "//div[@data-id]")
    SCROLL_DOWN = "//div[@class='PRE_LOGIN_MORE_INFO css-splkkx']"

